### ISSUE TITLE
Issue about Input Value Error in the training

### ISSUE THREAD

**Issue by MasayaKikuzawa** [LeeDongYeun/keras-m2det#1]
I wanna train the network with the datasets like Pascal_VOC datasets.
But when I start training, always face following error

`Traceback (most recent call last):
  File "c:\users\max\anaconda3\envs\m2det\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\max\anaconda3\envs\m2det\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\MAX\AppData\Roaming\Python\Python36\Scripts\m2det-train.exe\__main__.py", line 7, in <module>
  File "C:\Users\MAX\AppData\Roaming\Python\Python36\site-packages\keras_m2det\bin\train.py", line 522, in main
    validation_data=validation_generator
  File "C:\Users\MAX\AppData\Roaming\Python\Python36\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\MAX\AppData\Roaming\Python\Python36\site-packages\keras\engine\training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\MAX\AppData\Roaming\Python\Python36\site-packages\keras\engine\training_generator.py", line 220, in fit_generator
    reset_metrics=False)
  File "C:\Users\MAX\AppData\Roaming\Python\Python36\site-packages\keras\engine\training.py", line 1508, in train_on_batch
    class_weight=class_weight)
  File "C:\Users\MAX\AppData\Roaming\Python\Python36\site-packages\keras\engine\training.py", line 579, in _standardize_user_data
    exception_prefix='input')
  File "C:\Users\MAX\AppData\Roaming\Python\Python36\site-packages\keras\engine\training_utils.py", line 145, in standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected input_1 to have shape (320, 320, 3) but got array with shape (320, 427, 3)`

Even I used Original Pascal_VOC datasets VOC2007, I face same error

Do you have any idea?

My environment is 

> Windows 10, Python 3.6, tensorflow 1.13.1
Other library is following your repository

**Comment by LeeDongYeun** [comment]
Hi, thanks for your attention.

for m2det, image should be resized to same column and row.
And because of some restriction of model, I implemented each backbone got particular input size.
you can see the input for each backbone in keras-m2det/model.

each image is resized before going to model. You can see that code in preprocessing/generator.py resize_image. They got args image_min_side, image_max_side. You can change it with args with training code.

So, for pascal_VOC, when you use resnet, image_min_side = 640 image_max_side = 640
when you use vgg, image_min_side = 320 image_max_side = 640

Thanks.

**Comment by junyongyou** [comment]
Thanks a lot for the excellent work. I tried to use the model with respect on my own dataset in CSV format. I also got this input shape issue while I am using resnet. This model requires same image width and height. However, if an original image has different width and height, and as the image_resize in the scripts actually uses one scale factor to resize image width and height, then the resized image will still have different width and height, even though I set image_min_size=640 and image_max_size=640. So, should I change the scripts to resize all training (val) images to same width and height? Thank you very much.

**Comment by LeeDongYeun** [comment]
https://github.com/LeeDongYeun/keras-m2det/blob/677af3f548594671745bd80bae39f92f26e8ebe7/keras_m2det/utils/image.py#L181

above is resize function. I think if you are using different scaled images, you should change this function.

**Comment by junyongyou** [comment]
Thank you. Since resize_image also returns the scale factor, which should be used in the evaluator, right? So I guess I need to change the evaluator as well? Is that correct?

**Comment by LeeDongYeun** [comment]
right. You need to change it too. It is used when drawing bounding boxes. But I recommend you to use same size of images. Resize all images to same size and use them when training.

**Comment by junyongyou** [comment]
Thank you. I am trying it and will see how it works in my case.

**Comment by GalymzhanAbdimanap** [comment]
Thanks for the work you've done. @Junyongyou can you share with the code that you changed for your csv dataset? Thank you
